### ISSUE TITLE
question about particle swarm optimization modification

### ISSUE THREAD

**Issue by natureoptics7** [Valdecy/pyCombinatorial#2]
Thank you for your hard work and effort!
I wonder if it is possible to add more parameters just for particle swarm optimization. 
Only two parameter optimizations are now available. (For example, 50 parameters, not 2)

**Comment by Valdecy** [comment]
I'm sorry, but in pyCombinatorial, I have not implemented Particle Swarm Optimization. Or are you talking about another method?

**Comment by natureoptics7** [comment]
oh, i did mistake. I rewrite the question in pyMetaheuristic board. Thank you.
