### ISSUE TITLE
Simulated Annealing error

### ISSUE THREAD

**Issue by hnnam0906** [Valdecy/pyCombinatorial#3]
Hi @Valdecy,

I try to test the Simulated Annealing algo in the Colab but it throws the below error:
"ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part."

![image](https://github.com/user-attachments/assets/f9cac422-f295-4939-80b6-0f672b1694b5)

Please kindly support to solve the issue. 

Thanks

**Comment by hnnam0906** [comment]
Hi @Valdecy,
I think i can fix the issue by replacing the np.copy by copy.deepcopy, but currently i face with the other issue

algorithm/sa.py:122: RuntimeWarning: overflow encountered in exp
p = np.exp(-delta/temperature)

**Comment by Valdecy** [comment]
Hi there! Please try pyCombinatorial version 1.8.1. If you’re still experiencing issues, feel free to share your instance and parameters with me, and I'll do my best to reproduce and resolve the error.

Best regards,
Valdecy
